// Mock data used when no database is connected (demo/preview mode)

export const MOCK_USER = {
  id: "demo-user-1",
  email: "demo@stakearena.gg",
  username: "DemoPlayer",
  avatar: null,
  balance: 250.0,
  totalWins: 18,
  totalLosses: 7,
  totalEarnings: 842.5,
  createdAt: new Date("2024-09-01"),
  updatedAt: new Date(),
  challengesCreated: [
    {
      id: "ch-1",
      game: "valorant",
      stakeAmount: 50,
      status: "COMPLETED" as const,
      createdAt: new Date("2025-03-18"),
      opponent: { username: "SnipeKing99" },
    },
    {
      id: "ch-2",
      game: "chess",
      stakeAmount: 25,
      status: "ACTIVE" as const,
      createdAt: new Date("2025-03-20"),
      opponent: { username: "GrandMaster7" },
    },
    {
      id: "ch-3",
      game: "rocket-league",
      stakeAmount: 100,
      status: "PENDING" as const,
      createdAt: new Date("2025-03-21"),
      opponent: null,
    },
    {
      id: "ch-4",
      game: "fifa",
      stakeAmount: 25,
      status: "COMPLETED" as const,
      createdAt: new Date("2025-03-15"),
      opponent: { username: "GoalScorer" },
    },
    {
      id: "ch-5",
      game: "cod",
      stakeAmount: 75,
      status: "CANCELLED" as const,
      createdAt: new Date("2025-03-10"),
      opponent: null,
    },
  ],
};

export const MOCK_CHALLENGES = [
  {
    id: "ch-open-1",
    game: "valorant",
    stakeAmount: 50,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-22T10:00:00"),
    creator: { id: "u1", username: "SnipeKing99", avatar: null, totalWins: 24, totalLosses: 9 },
  },
  {
    id: "ch-open-2",
    game: "chess",
    stakeAmount: 25,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-22T09:30:00"),
    creator: { id: "u2", username: "GrandMaster7", avatar: null, totalWins: 41, totalLosses: 6 },
  },
  {
    id: "ch-open-3",
    game: "rocket-league",
    stakeAmount: 100,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-22T08:15:00"),
    creator: { id: "u3", username: "RocketPro", avatar: null, totalWins: 15, totalLosses: 12 },
  },
  {
    id: "ch-open-4",
    game: "fifa",
    stakeAmount: 10,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-21T22:00:00"),
    creator: { id: "u4", username: "GoalScorer", avatar: null, totalWins: 8, totalLosses: 5 },
  },
  {
    id: "ch-open-5",
    game: "cod",
    stakeAmount: 75,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-21T20:45:00"),
    creator: { id: "u5", username: "HeadshotOnly", avatar: null, totalWins: 31, totalLosses: 14 },
  },
  {
    id: "ch-open-6",
    game: "clash-royale",
    stakeAmount: 25,
    status: "PENDING" as const,
    createdAt: new Date("2025-03-21T19:00:00"),
    creator: { id: "u6", username: "ClashLord", avatar: null, totalWins: 52, totalLosses: 21 },
  },
];

export const MOCK_LEADERBOARD = [
  { id: "u6", username: "ClashLord",    avatar: null, totalWins: 52, totalLosses: 21, totalEarnings: 2340.00 },
  { id: "u2", username: "GrandMaster7", avatar: null, totalWins: 41, totalLosses:  6, totalEarnings: 1875.50 },
  { id: "u5", username: "HeadshotOnly", avatar: null, totalWins: 31, totalLosses: 14, totalEarnings: 1420.25 },
  { id: "u1", username: "SnipeKing99",  avatar: null, totalWins: 24, totalLosses:  9, totalEarnings:  980.00 },
  { id: "demo-user-1", username: "DemoPlayer", avatar: null, totalWins: 18, totalLosses: 7, totalEarnings: 842.50 },
  { id: "u3", username: "RocketPro",    avatar: null, totalWins: 15, totalLosses: 12, totalEarnings:  620.75 },
  { id: "u4", username: "GoalScorer",   avatar: null, totalWins:  8, totalLosses:  5, totalEarnings:  310.00 },
  { id: "u7", username: "NightOwl",     avatar: null, totalWins:  7, totalLosses:  4, totalEarnings:  275.00 },
  { id: "u8", username: "FragMaster",   avatar: null, totalWins:  6, totalLosses:  6, totalEarnings:  200.00 },
  { id: "u9", username: "SweatLord",    avatar: null, totalWins:  4, totalLosses:  3, totalEarnings:  145.50 },
];
